In [26]:
import numpy as np
import pandas as pd

In [3]:
X_culled = pd.read_excel("X_culled.xlsx")

In [4]:
X_culled.columns

Int64Index([   1,    2,    3,    4,    6,    7,    8,    9,   10,   11,
            ...
            1221, 1225, 1227, 1229, 1233, 2001, 2011, 2013, 2015, 2017],
           dtype='int64', length=179)

In [6]:
X_culled.head()

1     2     3     4     6     7     8     9     10    11    ...  1221  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     1     0     0     0     0     0     0     0     1  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     1     1  ...     0   
4     0     1     0     0     0     0     0     0     0     0  ...     0   

   1225  1227  1229  1233  2001  2011  2013  2015  2017  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     1     0  
2     0     0     0     0     0     0     0     1     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     1     1  

[5 rows x 179 columns]

In [8]:
X_culled.describe()

1           2           3           4           6           7     \
count  131.000000  131.000000  131.000000  131.000000  131.000000  131.000000   
mean     0.007634    0.145038    0.007634    0.007634    0.030534    0.022901   
std      0.087370    0.353491    0.087370    0.087370    0.172713    0.150161   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

             8           9           10          11    ...        1221  \
count  131.000000  131.000000  131.000000  131.000000  ...  131.000000   
mean     0.091603    0.099237    0.221374    0.335878  ...    0.114504   
std      0.289572    0.300127    0.416766    0.474109  ...    0.319645   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
50%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
75%      0.000000    0.000000    0.000000    1.000000  ...    0.000000   
max      1.000000    1.000000    1.000000    1.000000  ...    1.000000   

             1225        1227        1229        1233        2001        2011  \
count  131.000000  131.000000  131.000000  131.000000  131.000000  131.000000   
mean     0.076336    0.038168    0.183206    0.022901    0.068702    0.022901   
std      0.266554    0.192337    0.388320    0.150161    0.253918    0.150161   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

             2013        2015        2017  
count  131.000000  131.000000  131.000000  
mean     0.068702    0.305344    0.198473  
std      0.253918    0.462321    0.400381  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%      0.000000    1.000000    0.000000  
max      1.000000    1.000000    1.000000  

[8 rows x 179 columns]

In [19]:
#for column in X_culled.columns:
 #   print(X_culled[column].value_counts())

In [49]:
numb = np.array([[0, 0]])
for column in X_culled.columns:
    a = np.array([[column, len(X_culled[X_culled[column] == 1])]])
    numb = np.append(numb, a, axis=0)
    
def Sort(li): 
    return(sorted(li, key = lambda x: -x[1]))

Sort(numb)

[array([108,  57]),
 array([114,  55]),
 array([80, 54]),
 array([115,  54]),
 array([78, 53]),
 array([79, 52]),
 array([109,  50]),
 array([101,  49]),
 array([102,  49]),
 array([106,  49]),
 array([105,  48]),
 array([74, 47]),
 array([100,  45]),
 array([113,  45]),
 array([11, 44]),
 array([168,  44]),
 array([99, 43]),
 array([104,  42]),
 array([147,  42]),
 array([24, 41]),
 array([75, 40]),
 array([169,  40]),
 array([2015,   40]),
 array([73, 39]),
 array([25, 37]),
 array([56, 37]),
 array([28, 36]),
 array([81, 36]),
 array([173,  36]),
 array([150,  35]),
 array([116,  34]),
 array([117,  34]),
 array([124,  34]),
 array([139,  34]),
 array([111,  32]),
 array([148,  32]),
 array([174,  32]),
 array([112,  31]),
 array([140,  31]),
 array([10, 29]),
 array([82, 29]),
 array([129,  29]),
 array([167,  29]),
 array([76, 28]),
 array([103,  28]),
 array([107,  28]),
 array([144,  28]),
 array([175,  28]),
 array([12, 26]),
 array([2017,   26]),
 array([149,  25]),
 array([17